reviews/urls.py
from . import views
from django.urls import path

# Difference between this urls.py and the other urls.py in 'saninvicta' foldeR?
urlpatterns = [
    path('', views.home, name='home'),
    path('membership/', views.ReviewList.as_view(), name='membership'),
    path('membership/<slug:slug>/', views.ReviewDetail.as_view(), name='review'),
    path('add_review/', views.add_review, name='add_review'),
    path('update_review/<int:review_id>/', views.update_review, name='update_review'),
    path('delete_review/<int:review_id>/', views.delete_review, name='delete_review'),
]

saninvicta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('reviews.urls'), name='reviews_urls'),
]

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, 'Draft'), (1, 'Published'))


class Review(models.Model):

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='reviews_likes', blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):

    review = models.ForeignKey(
        Review, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.author}"

reviews/forms.py
from django import forms
from .models import Comment, Review


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'content', 'featured_image', 'status')

reviews/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic, View
from django.utils.text import slugify
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Review
from .forms import CommentForm, ReviewForm


def home(request):
    template = 'home.html'
    context = {}
    return render(request, template, context)


class ReviewList(generic.ListView):
    model = Review
    queryset = Review.objects.filter(status=1).order_by('-created_on')
    template_name = 'reviews/membership.html'
    paginate_by = 6


class ReviewDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Review.objects.filter(status=1)
        review = get_object_or_404(queryset, slug=slug)
        comments = review.comments.filter(approved=True).order_by('created_on')
        liked = False
        if review.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "reviews/review.html",
            {
                "review": review,
                "comments": comments,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )
    
    def post(self, request, slug, *args, **kwargs):

        queryset = Review.objects.filter(status=1)
        review = get_object_or_404(queryset, slug=slug)
        comments = review.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if review.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.author = request.user
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "reviews/review.html",
            {
                "review": review,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )


def add_review(request):
    review_form = ReviewForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if review_form.is_valid():
            review_form.instance.slug = slugify(request.POST.get('title'))
            review_form.instance.author = request.user
            review_form.save()
            messages.success(request, 'Thank you for your review!')
            return redirect('home')
        messages.error(request, 'Error, please try again')
    template = 'reviews/add_review.html'
    context = {
        'review_form': review_form,
    }
    return render(request, template, context)


def update_review(request, review_id):
    user = get_object_or_404(User, username=request.user.username)
    review = get_object_or_404(Review, id=review_id)
    if user != review.author:
        messages.error(request, 'Access denied')
        return redirect('home')
    review_form = ReviewForm(request.POST or None, request.FILES or None, instance=review)
    if request.method == 'POST':
        if review_form.is_valid():
            review_form.instance.slug = slugify(request.POST.get('title'))
            review_form.instance.author = request.user
            review_form.save()
            messages.success(request, 'Review updated successfully!')
            return redirect('home')
        messages.error(request, 'Error, please try again')
    template = 'reviews/update_review.html'
    context = {
        'review': review,
        'review_form': review_form,
    }
    return render(request, template, context)


def delete_review(request, review_id):
    user = get_object_or_404(User, username=request.user.username)
    review = get_object_or_404(Review, id=review_id)
    if user != review.author:
        messages.error(request, 'Access denied')
        return redirect('home')
    review.delete()
    messages.success(request, 'Review deleted')
    return redirect('home')

reviews/templates/reviews/add_review.html
{% extends 'base.html' %} {% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <h1 class="post-title">Add review</h1>
                <form action="{% url 'add_review' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ review_form.as_p }}
                    <button type="submit">Submit review</button>
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

reviews/templates/reviews/membership.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}

<article class="container-fluid mt-3">
    <section class="callout jumbotron text-center">
        <h4>Helping young men improve their life</h4>
        <p>Sign up & get access to valuable content
            <s class="d-none d-sm-inline">$9.99 monthly!</s>
            <span class="d-inline d-sm-none"><br></span>
            <strong><mark>December Deal: $4.99 monthly!</mark></strong></p>
        <p class="text-muted"><small><strong>Membership fee</strong> of $10.00 will be added first month
                only</small></p>
    </section>
    <hr>
    <section class="motivation">
        <div class="row">
            <div class="col-12 my-5">
                <h2 class="why">Why should I improve my life?</h2>
                <div class="motivation-quote">
                    <p class="text-uppercase">Masculinity is on the verge of extinction today. Honor your family by
                        becoming a strong masculine figure. Take action & accountability. 
                        The feeling of having other men respect you & women admire you is unbeatable. Join the movement today!</p>
                </div>
            </div>
        </div>
        <hr>
    </section>
    <section class="quotes">
        <h2>The four core components for Masculinity</h2>
        <div class="container-fluid">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">
              <div class="col-12 col-md-6">
                <div class="quote">
                    <div class="media">
                        <img src="{% static 'images/strength1.jpg' %}" class="rounded-circle img-responsive mr-3" height="100"
                            width="100">
                        <div class="media-body">
                            <h3>Strength</h3>
                            <p>Remember when you watched all the cartoon movies or read those comic books?
                                Why did you like the main character or superhero so much?
                                Today we don't see that sort of Strength being showcased in media or even in real
                                life.
                                I mean, when was the last time YOU stod up to something or someone?
                            </p>
                        </div>
                    </div>
                </div>
              </div>
              <div class="col-12 col-md-6">
                <div class="quote">
                    <div class="media">
                        <img src="{% static 'images/honor.jpg' %}" class="rounded-circle img-responsive mr-3" height="100"
                            width="100">
                        <div class="media-body">
                            <h3>Honor</h3>
                            <p>Honor is the act of standing ten toes down on things that you believe in.
                                Don't do it for validation, do it for yourself or your family.
                            </p>
                        </div>
                    </div>
                </div>
              </div>
               <div class="col-12 col-md-6">
                    <div class="quote">
                        <div class="media">
                            <img src="{% static 'images/courage.jpg' %}" class="rounded-circle img-responsive mr-3" height="100"
                            width="100">
                            <div class="media-body">
                                <h3>Courage</h3>
                                <p>Doing things regardless of reaction.
                                    When we do things and people or even the whole world judges us,
                                    will we back down or keep our head up?
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <div class="quote">
                        <div class="media">
                            <img src="{% static 'images/mastery.jpg' %}" class="rounded-circle img-responsive mr-3" height="100"
                            width="100">
                            <div class="media-body">
                                <h3>Mastery</h3>
                                <p>Having a arsenal of knowledge or attributes is a very crucial part of being a man in
                                    todays
                                    society.
                                    It has always been admirable when a man knows how to operate in life with several
                                    skills.
                                    These things can be anything, how to program, building something physical, surviving
                                    in the
                                    wilderness etc.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </section>
     <!-- FIND HOW TO MAKE MEMBERSHIP SECTION INLINE -->
     <section class="subscription">
        <h3 class="text-uppercase">Memberships</h3>
        <div class="col-12 col-md-6 col-lg-4 my-3">
            <br>
            <h4>Free</h4>
            <ul>
                <li>Access to over 100+ videos</li>
                <li>Free weekly tips</li>
                <li>Random offers on our products</li>
            </ul>
        </div>
        <div class="col-12 d-md-inline d-lg-inline col-lg-4 my-3">
            <br>
            <h4>Silver <span class="badge badge-info">December Deal</span></h4>
            <ul>
                <li>Exclusive videos</li>
                <li>50% discount on merch</li>
                <li>Zoom Meeting call up to 2x weekly</li>
                <li>Invitation to WhatsApp group chat</li>
                <li>Free weekly tips</li>
                <li>Random offers on our products</li>
            </ul>
        </div>
        <div class="col-12 d-md-inline d-lg-inline col-lg-4 my-3">
            <br>
            <h4>Gold</h4>
            <ul>
                <li>1on1 calls with creators</li>
                <li>Free hoodie & e-book</li>
                <li>Zoom Meeting call up to 2x weekly</li>
                <li>Exclusive videos</li>
                <li>Invitation to WhatsApp group chat</li>
                <li>Free weekly tips</li>
                <li>Random offers on our products</li>
            </ul>
        </div>

    </section>
</article>


<div class="container-fluid">
    <div class="row">
        <div class="col-12 mx-auto">
            <a href="{% url 'add_review' %}" class="btn btn-dark">Leave review!</a>
        </div>
    </div>
    <div class="row">

        <!-- loop the reviews -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for review in review_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in review.featured_image.url %}
                                <img class="card-img-top"
                                    src="{% static 'images/me_kurdistan.png' %}">
                                {% else %}
                                <img class="card-img-top" src=" {{ review.featured_image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ review.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'review' review.slug  %}" class="post-link">
                                <h2 class="card-title">{{ review.title }}</h2>
                                <p class="card-text">{{ review.excerpt }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ review.created_on}} <i class="far fa-heart"></i>
                                {{ review.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

reviews/templates/reviews/review.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ review.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ review.author }} | {{ review.created_on }}</p>
                {% if request.user == review.author %}
                <a class="btn btn-dark" href="{% url 'update_review' review.id %}">Edit</a>
                <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal-delete">Delete</a>
                <!-- Modal -->
                <div class="modal fade" id="modal-delete" tabindex="-1" aria-labelledby="modaldeleteLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="modaldeleteLabel">Delete review</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Are you sure you want to delete this review?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                                <a class="btn btn-danger" href="{% url 'delete_review' review.id %}">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in review.featured_image.url %}
                <img src="{% static 'images/me_kurdistan.png' %}" width="100%">
                {% else %}
                <img src="{{ review.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text ">
                    {{ review.content|safe }}
                </p>
                <div class="row">

                    <div class="col-1">
                        <!-- The number of likes goes before the closing strong tag -->
                        <strong class="text-secondary"><i class="far fa-heart"></i> {{ review.number_of_likes }}
                        </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- For later -->

                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting approval
                </div>
                {% else %}
                {% if user.is_authenticated %}

                <h3>Leave a comment:</h3>
                <p>Commenting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>


{% endblock content %}

reviews/templates/reviews/update_review.html
{% extends 'base.html' %} {% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <h1 class="post-title">Update {{ review.title }}</h1>
                <form action="{% url 'update_review' review.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ review_form.as_p }}
                    <button type="submit">Submit changes</button>
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>SanInvicta</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><span class="brand">I<span class="red-o">n</span>victa<span
                        class="thin">|per</span><span class="thin">|San</span></span></span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'membership' %}">Membership</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}

                </ul>
                <span class="navbar-text text-muted">
                    Self-improvement made simple
                </span>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="offset-md-2">
                    {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                        {{ message | safe }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Made by San Zangana</p>
        <p class="m-0 text-center text-white">Connect with me! <i class="fab fa-facebook-square ms-3"></i>
            <i class="fab fa-twitter-square ms-3"></i>
            <i class="fab fa-instagram-square ms-3"></i>
            <i class="fab fa-youtube-square ms-3"></i></p>
    </footer>
    <script>
        setTimeout(function() {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
        
    </script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section class="banner">
    <div class="container-ny">
            <div class="img-text">
                <img src="{% static 'images/berg_img.jpg' %}" alt="picture of me standing in my city" class="bg-img">
                <h1 class="img-header"><strong>Welcome!</strong></h1>
            </div>
            <h2 class="img-h2">Your guide to Self-improvement</h2>
        </div>
    </div>
</section>
<section class="brand-logo">
    <div class="container-ny">
        <div class="brand-logo-inner">
            <h5>Finance</h5>
            <h5>Health</h5>
            <h5>Fitness</h5>
            <h5>Fashion</h5>
        </div>
    </div>
</section>
<!-- First hook (marketing) -->
<section class="sec1">
    <div class="container-ny">
        <div class="sec1-in">
            <div class="text text-left">
                <h2><strong>ACNE TREATMENT</strong>
                </h2>
            </div>
            <div class="text text-right">
                <p>If you struggle with acne and have no other solutions left than to take medications... I GOt THE SOLUTION!
                    Below here you can see my own issues with acne, this strategy is 100% guaranteed to work.
                    No magic tricks, no extra money, all it takes is a simple way to figure out which foods your body reacts to.
                    If you buy the <a href="{% url 'membership' %}">MEMBERSHIP</a> here and book a FREE call with me, 
                    you will see results within weeks AND feel amazing!</p>
            </div>
        </div>
        <div>
            <img class="sec1-img" src="{% static 'images/acne_noacne.jpg' %}" alt="">
        </div>
    </div>
</section>
<!-- Second hook (marketing) -->
<section class="sec2">
    <div class="container-ny">
        <div class="sec2-in">
            <div class="text text-left">
                <h2><strong>FAT LOSS</strong></h2>
                    <p>As you can see in this progress video, I have also been <em>overweight.</em>I really
                        struggled with losing weight/fat and <strong>build muscle</strong> at the same time.
                        But once I applied the knowledge that <strong>YOU</strong> will learn about, everything
                        changed.
                        Some may call it "strict", however, I would call it the proper human diet. A diet where
                        you feed the body the essential
                        nutrients needed to both preserve muscle mass but also <em>build it.</em>
                    </p>
            </div>
            <div>
                <video width="320" height="240" controls>
                    <source src="{% static 'videos/progress-vid.mp4' %}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
        </div>
    </div>
</section>     
{% endblock content %}